name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Deploy to server
      run: |
        # Aqui você adiciona os comandos para fazer deploy
        # Exemplo: rsync, scp, ou comandos específicos do seu servidor
        echo "Build completed successfully!"
        echo "Files ready for deployment in dist/ folder"
